import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ReactQueryProviders from "./utils/reactQueryProvider";
import { Suspense } from "react";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import Devtool from "./_components/devtool";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Andy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

{
  return (
    <html lang="en">
        <body className={inter.className}>
          <ReactQueryProviders>
            {children}
            <Devtool />
          </ReactQueryProviders>
        </body>
    </html>
  );
}
