stages:
  - build
  - notify

build_job:
  stage: build
  script:
    - npm install
    - npm run build # 프로젝트를 빌드합니다.
  only:
    refs:
      - merge_requests
    changes:
      - "**/*" # 모든 변경사항에 대해 빌드를 실행합니다.
  except:
    - master   
notify_success:
  stage: notify
  script:
    - >
      curl -X POST -H 'Content-type: application/json' --data '{"text": "'"$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"'브랜치를 '"$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"'에 머지하기 전 빌드가 성공했습니다!"}' https://meeting.ssafy.com/hooks/inxg4tbutiff9n8zo49wam5hde
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success

